[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_functions = test_*
python_classes = Test*
asyncio_mode = auto
norecursedirs = .venv temp_cache uploads static __pycache__ alembic
