import React, { useRef } from 'react';
import { X, Printer, Download, CheckCircle2, ShieldCheck, FileCheck } from 'lucide-react';
import './GovernmentReportPrintModal.css';

export default function GovernmentReportPrintModal({
  isOpen,
  onClose,
  template = 'officer_performance',
  reportData,
  selectedOfficerId = 'all',
  selectedPetition
}) {
  const printRef = useRef(null);

  if (!isOpen || !reportData) return null;

  const meta = reportData.reportMetadata || {};
  let officers = reportData.officersDirectory || [];
  const petitions = reportData.petitionProcessingHistory || [];
  const logs = reportData.recentAuditLogs || [];
  const analysis = reportData.intakeAnalysis || {};

  if (selectedOfficerId && selectedOfficerId !== 'all') {
    officers = officers.filter(o => String(o.id) === String(selectedOfficerId));
  }

  const handlePrint = () => {
    window.print();
  };

  const generatedDateStr = new Date(meta.generatedAt || Date.now()).toLocaleString('en-IN', {
    dateStyle: 'full',
    timeStyle: 'medium'
  });

  return (
    <div className="govt-print-modal-overlay" role="dialog" aria-modal="true" aria-label="Official Government Report Preview">
      <div className="govt-print-modal-container">
        
        {/* TOP TOOLBAR (HIDDEN ON PRINT) */}
        <div className="govt-print-modal-toolbar no-print">
          <div className="govt-toolbar-info">
            <ShieldCheck size={18} className="govt-toolbar-icon" />
            <span>Official Government Document Preview • Bookman Old Style & Marudham Tamil Font</span>
          </div>

          <div className="govt-toolbar-actions">
            <button
              type="button"
              className="govt-print-btn"
              onClick={handlePrint}
              title="Print or Save as PDF"
            >
              <Printer size={15} />
              <span>Print / Save as Official PDF</span>
            </button>
            <button
              type="button"
              className="govt-close-btn"
              onClick={onClose}
              title="Close Preview"
            >
              <X size={18} />
            </button>
          </div>
        </div>

        {/* PRINTABLE OFFICIAL DOCUMENT SHEET */}
        <div className="govt-document-sheet" ref={printRef}>

          {/* OFFICIAL HEADER BANNER */}
          <header className="govt-doc-header">
            <div className="govt-header-top">
              <img src="/tn-emblem.png" alt="Government of Tamil Nadu" className="govt-doc-emblem" />
              <div className="govt-header-titles">
                <h1 className="govt-main-title">GOVERNMENT OF TAMIL NADU</h1>
                <p className="govt-sub-title">REVENUE & DISASTER MANAGEMENT DEPARTMENT • ERODE DISTRICT COLLECTORATE</p>
                <h2 className="govt-doc-type">
                  {template === 'officer_performance' && 'AI ADMINISTRATIVE CO-PILOT — OFFICER AUDIT & PERFORMANCE REPORT'}
                  {template === 'audit_logs' && 'SYSTEM AUDIT & ADMINISTRATIVE SECURITY LOG REPORT'}
                  {template === 'single_petition' && `COMPREHENSIVE PETITION DOSSIER & FULL FORM RECORD`}
                  {template === 'intake_report' && 'TOTAL PETITIONS RECEIVED & MULTI-CHANNEL INTAKE REPORT'}
                </h2>
              </div>
            </div>
            <div className="govt-gold-divider" />
          </header>

          {/* METADATA BOX */}
          <section className="govt-meta-box">
            <div className="govt-meta-col">
              <div className="govt-meta-row">
                <span className="govt-meta-label">District / Office:</span>
                <span className="govt-meta-val">Erode District Collectorate (Public Grievance Cell)</span>
              </div>
              <div className="govt-meta-row">
                <span className="govt-meta-label">Generated Date:</span>
                <span className="govt-meta-val">{generatedDateStr}</span>
              </div>
            </div>
            <div className="govt-meta-col">
              <div className="govt-meta-row">
                <span className="govt-meta-label">Generated By:</span>
                <span className="govt-meta-val">{meta.generatedBy || 'District Administrator'}</span>
              </div>
              <div className="govt-meta-row">
                <span className="govt-meta-label">Security Classification:</span>
                <span className="govt-meta-val govt-secure-tag">OFFICIAL / RESTRICTED</span>
              </div>
            </div>
          </section>

          {/* ========================================================================= */}
          {/* TEMPLATE 1: OFFICER PERFORMANCE */}
          {/* ========================================================================= */}
          {template === 'officer_performance' && (
            <div className="govt-doc-content">
              {/* KPI Strip */}
              <div className="govt-kpi-grid">
                <div className="govt-kpi-card">
                  <div className="govt-kpi-val">{meta.totalOfficers || officers.length}</div>
                  <div className="govt-kpi-lbl">Total Officers</div>
                </div>
                <div className="govt-kpi-card">
                  <div className="govt-kpi-val">{meta.activeOfficers || 0}</div>
                  <div className="govt-kpi-lbl">Active Sessions</div>
                </div>
                <div className="govt-kpi-card">
                  <div className="govt-kpi-val">{meta.totalPetitions || petitions.length}</div>
                  <div className="govt-kpi-lbl">Total Petitions</div>
                </div>
                <div className="govt-kpi-card">
                  <div className="govt-kpi-val highlight">{meta.totalApproved || 0}</div>
                  <div className="govt-kpi-lbl">Approved / Resolved</div>
                </div>
              </div>

              <h3 className="govt-section-heading">1. Officer Directory & Petition Resolution Breakdown</h3>
              <table className="govt-official-table">
                <thead>
                  <tr>
                    <th style={{ width: '15%' }}>Officer ID</th>
                    <th style={{ width: '25%' }}>Official Name</th>
                    <th style={{ width: '25%' }}>Department / Designation</th>
                    <th style={{ width: '8%', textAlign: 'center' }}>Total</th>
                    <th style={{ width: '9%', textAlign: 'center' }}>Approved</th>
                    <th style={{ width: '9%', textAlign: 'center' }}>In Review</th>
                    <th style={{ width: '9%', textAlign: 'center' }}>Resolution %</th>
                  </tr>
                </thead>
                <tbody>
                  {officers.map(off => (
                    <tr key={off.id}>
                      <td className="bold-cell">{off.id}</td>
                      <td>
                        <strong>{off.name}</strong>
                        {off.nameTamil && <span className="tamil-text d-block">({off.nameTamil})</span>}
                      </td>
                      <td>
                        <div>{off.department}</div>
                        <small className="text-muted">{off.designation}</small>
                      </td>
                      <td className="text-center bold-cell">{off.totalProcessed || 0}</td>
                      <td className="text-center success-cell">{off.approved || 0}</td>
                      <td className="text-center">{off.inProgress || 0}</td>
                      <td className="text-center bold-cell success-cell">{off.successRate || '100%'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* ========================================================================= */}
          {/* TEMPLATE 2: AUDIT LOGS */}
          {/* ========================================================================= */}
          {template === 'audit_logs' && (
            <div className="govt-doc-content">
              <h3 className="govt-section-heading">
                Chronological System & Officer Audit History Trail
                <span className="govt-heading-badge">
                  {selectedOfficerId === 'all' ? 'All Officers' : `Officer: ${selectedOfficerId}`} ({logs.length} entries)
                </span>
              </h3>
              <table className="govt-official-table">
                <thead>
                  <tr>
                    <th style={{ width: '20%' }}>Timestamp</th>
                    <th style={{ width: '16%' }}>Officer ID</th>
                    <th style={{ width: '18%' }}>Category</th>
                    <th style={{ width: '16%' }}>Action Type</th>
                    <th style={{ width: '30%' }}>Audit Event Details</th>
                  </tr>
                </thead>
                <tbody>
                  {logs.slice(0, 100).map(l => (
                    <tr key={l.id || l.timestamp}>
                      <td>{l.timestamp ? new Date(l.timestamp).toLocaleString('en-IN') : '—'}</td>
                      <td className="bold-cell">{l.officer_id || 'SYSTEM'}</td>
                      <td>{l.category || 'GDP Assistant'}</td>
                      <td>{l.action || l.type || 'ACTIVITY'}</td>
                      <td className="tamil-text">{l.details || '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* ========================================================================= */}
          {/* TEMPLATE 3: SINGLE PETITION DOSSIER */}
          {/* ========================================================================= */}
          {template === 'single_petition' && selectedPetition && (
            <div className="govt-doc-content">
              <div className="govt-single-pet-banner">
                <div className="govt-pet-id">
                  <strong>Petition Number:</strong> {selectedPetition.petitionNumber || selectedPetition.id}
                </div>
                <div className="govt-pet-badges">
                  <span className={`status-pill ${selectedPetition.status === 'Approved' ? 'is-success' : 'is-pending'}`}>
                    Status: {selectedPetition.status || 'Approved'}
                  </span>
                  <span className="priority-pill">
                    Priority: {selectedPetition.priority || 'MEDIUM'}
                  </span>
                </div>
              </div>

              <h3 className="govt-section-heading">1. Applicant Identity & Geographic Hierarchy</h3>
              <table className="govt-keyvalue-table">
                <tbody>
                  <tr>
                    <th style={{ width: '25%' }}>Petitioner Name:</th>
                    <td style={{ width: '25%' }} className="tamil-text bold-cell">{selectedPetition.applicantName || '—'}</td>
                    <th style={{ width: '25%' }}>District:</th>
                    <td style={{ width: '25%' }}>{selectedPetition.district || 'Erode'}</td>
                  </tr>
                  <tr>
                    <th>Mobile Number:</th>
                    <td>{selectedPetition.mobile || '—'}</td>
                    <th>Taluk / Firka:</th>
                    <td className="tamil-text">{selectedPetition.taluk || 'Erode'} / {selectedPetition.firka || 'Erode Urban'}</td>
                  </tr>
                  <tr>
                    <th>Email Address:</th>
                    <td>{selectedPetition.email || '—'}</td>
                    <th>Village / Block:</th>
                    <td className="tamil-text">{selectedPetition.village || 'Surampatti'} / {selectedPetition.block || 'Erode'}</td>
                  </tr>
                  <tr>
                    <th>Residential Address:</th>
                    <td colSpan={3} className="tamil-text">{selectedPetition.address || 'Erode District, Tamil Nadu'}</td>
                  </tr>
                </tbody>
              </table>

              <h3 className="govt-section-heading" style={{ marginTop: '16px' }}>2. Administrative Grievance Classification</h3>
              <table className="govt-keyvalue-table">
                <tbody>
                  <tr>
                    <th style={{ width: '25%' }}>Assigned Department:</th>
                    <td style={{ width: '25%' }} className="bold-cell">{selectedPetition.department || 'Revenue Administration'}</td>
                    <th style={{ width: '25%' }}>Intake Channel:</th>
                    <td style={{ width: '25%' }}>{selectedPetition.intakeChannel || 'Collectorate Public Counter'}</td>
                  </tr>
                  <tr>
                    <th>Grievance Category:</th>
                    <td className="tamil-text">{selectedPetition.category || 'Patta & Land Records'}</td>
                    <th>Grievance Sub-Category:</th>
                    <td className="tamil-text">{selectedPetition.subCategory || 'Patta Transfer'}</td>
                  </tr>
                  <tr>
                    <th>Processing Officer:</th>
                    <td>{selectedPetition.officerName || 'Assigned Officer'} ({selectedPetition.officerId || '—'})</td>
                    <th>Submission Date:</th>
                    <td>{selectedPetition.createdAt ? new Date(selectedPetition.createdAt).toLocaleString('en-IN') : 'Recent'}</td>
                  </tr>
                </tbody>
              </table>

              <h3 className="govt-section-heading" style={{ marginTop: '16px' }}>3. AI Grievance Synopsis & Action Items</h3>
              <table className="govt-keyvalue-table">
                <tbody>
                  <tr>
                    <th style={{ width: '28%' }}>Tamil Summary (மனு சுருக்கம்):</th>
                    <td className="tamil-text" style={{ lineHeight: '1.6' }}>
                      {selectedPetition.summaryTamil || selectedPetition.description || 'மனு விவரங்கள் பதிவு செய்யப்பட்டுள்ளன.'}
                    </td>
                  </tr>
                  <tr>
                    <th>English Synopsis:</th>
                    <td style={{ lineHeight: '1.6' }}>
                      {selectedPetition.summaryEnglish || 'Grievance recorded into the public registry for administrative action.'}
                    </td>
                  </tr>
                  <tr>
                    <th>Recommended Action Points:</th>
                    <td>
                      <ul style={{ margin: 0, paddingLeft: '18px' }}>
                        {Array.isArray(selectedPetition.actionItems) && selectedPetition.actionItems.length ? (
                          selectedPetition.actionItems.map((act, i) => (
                            <li key={i} className="tamil-text">{typeof act === 'object' ? (act.action || act.description || JSON.stringify(act)) : act}</li>
                          ))
                        ) : (
                          <>
                            <li className="tamil-text">வருவாய் ஆய்வாளர் மூலம் கள ஆய்வு மேற்கொள்ளுதல்</li>
                            <li className="tamil-text">கிராம நிர்வாக ஆவணங்கள் மற்றும் பட்டா பதிவேடுகளை சரிபார்த்தல்</li>
                            <li className="tamil-text">மாவட்ட வருவாய் அலுவலர் (DRO) ஒப்புதல் ஆணை வழங்குதல்</li>
                          </>
                        )}
                      </ul>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          )}

          {/* ========================================================================= */}
          {/* TEMPLATE 4: TOTAL INTAKE REPORT */}
          {/* ========================================================================= */}
          {template === 'intake_report' && (
            <div className="govt-doc-content">
              <div className="govt-kpi-grid">
                <div className="govt-kpi-card">
                  <div className="govt-kpi-val">{meta.totalPetitions || petitions.length}</div>
                  <div className="govt-kpi-lbl">Total Petitions Received</div>
                </div>
                <div className="govt-kpi-card">
                  <div className="govt-kpi-val highlight">{meta.totalApproved || 0}</div>
                  <div className="govt-kpi-lbl">Approved / Disposed</div>
                </div>
                <div className="govt-kpi-card">
                  <div className="govt-kpi-val">{meta.totalPending || 0}</div>
                  <div className="govt-kpi-lbl">Pending Review</div>
                </div>
              </div>

              <h3 className="govt-section-heading">1. Ingestion Breakdown by CM Grievance Channel</h3>
              <table className="govt-official-table">
                <thead>
                  <tr>
                    <th style={{ width: '70%' }}>CM Grievance Intake Channel</th>
                    <th style={{ width: '30%', textAlign: 'center' }}>Petitions Received</th>
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(analysis.byChannel || {}).map(([ch, cnt]) => (
                    <tr key={ch}>
                      <td>{ch}</td>
                      <td className="text-center bold-cell">{cnt}</td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <h3 className="govt-section-heading" style={{ marginTop: '16px' }}>2. Distribution Across Government Departments</h3>
              <table className="govt-official-table">
                <thead>
                  <tr>
                    <th style={{ width: '70%' }}>Department Name</th>
                    <th style={{ width: '30%', textAlign: 'center' }}>Total Grievances</th>
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(analysis.byDepartment || {}).map(([dept, cnt]) => (
                    <tr key={dept}>
                      <td>{dept}</td>
                      <td className="text-center bold-cell">{cnt}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* OFFICIAL SIGNATURE & SEAL BLOCK */}
          <footer className="govt-doc-footer">
            <div className="govt-sign-row">
              <div className="govt-stamp-box">
                <div className="govt-seal-circle">
                  <span>OFFICIAL SEAL</span>
                  <small>ERODE COLLECTORATE</small>
                </div>
              </div>
              <div className="govt-sign-box">
                <div className="govt-sign-line" />
                <strong>District Administrator / DRO</strong>
                <span>Erode District Collectorate</span>
                <small>Government of Tamil Nadu</small>
              </div>
            </div>
            <div className="govt-page-bottom-line">
              Official Government Document • District Collectorate Erode • Public Grievance Pre-Processing Cell
            </div>
          </footer>

        </div>
      </div>
    </div>
  );
}
