import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// Official Tamil Nadu Government Theme Colors
const COLOR_NAVY = [16, 44, 87];     // #102C57
const COLOR_GOLD = [218, 192, 163];   // #DAC0A3
const COLOR_SLATE = [71, 85, 105];   // #475569
const COLOR_LIGHT_BG = [248, 250, 252]; // #F8FAFC
const COLOR_BORDER = [226, 232, 240]; // #E2E8F0

function addOfficialHeader(doc, title = 'SYSTEM AUDIT REPORT', subtitle = 'REVENUE & DISASTER MANAGEMENT DEPARTMENT • ERODE DISTRICT COLLECTORATE') {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header Navy Banner
  doc.setFillColor(...COLOR_NAVY);
  doc.rect(0, 0, pageWidth, 28, 'F');

  // Gold Accent Line
  doc.setFillColor(...COLOR_GOLD);
  doc.rect(0, 28, pageWidth, 2, 'F');

  // Typography
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('GOVERNMENT OF TAMIL NADU', pageWidth / 2, 10, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text(subtitle, pageWidth / 2, 16, { align: 'center' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(234, 219, 200);
  doc.text(title, pageWidth / 2, 23, { align: 'center' });
}

function addOfficialFooters(doc) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const totalPages = doc.internal.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...COLOR_BORDER);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...COLOR_SLATE);
    doc.text(
      'Official Government Document • District Collectorate Erode • Public Grievance Pre-Processing Cell',
      margin,
      pageHeight - 7
    );
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - margin,
      pageHeight - 7,
      { align: 'right' }
    );
  }
}

/**
 * 1. Generates Executive Summary & Officer Performance Breakdown PDF
 */
export function generateGovernmentAuditPdf(reportData, selectedOfficerId = 'all') {
  const meta = reportData.reportMetadata || {};
  let officers = reportData.officersDirectory || [];
  const petitions = reportData.petitionProcessingHistory || [];

  if (selectedOfficerId && selectedOfficerId !== 'all') {
    officers = officers.filter(o => String(o.id) === String(selectedOfficerId));
  }

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  let currentY = 36;

  addOfficialHeader(doc, 'AI ADMINISTRATIVE CO-PILOT — OFFICER AUDIT & PERFORMANCE REPORT');

  const generatedDateStr = new Date(meta.generatedAt || Date.now()).toLocaleString('en-IN', {
    dateStyle: 'full',
    timeStyle: 'medium'
  });

  // Metadata Box
  doc.setFillColor(...COLOR_LIGHT_BG);
  doc.setDrawColor(...COLOR_BORDER);
  doc.roundedRect(margin, currentY, pageWidth - (margin * 2), 22, 2, 2, 'FD');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.text('Report Title:', margin + 4, currentY + 6);
  doc.setFont('helvetica', 'normal');
  doc.text('Officer Processed Petition Counts, Status & Redressal Performance', margin + 24, currentY + 6);

  doc.setFont('helvetica', 'bold');
  doc.text('District / Office:', margin + 4, currentY + 12);
  doc.setFont('helvetica', 'normal');
  doc.text('Erode District Collectorate (Public Grievance Cell)', margin + 30, currentY + 12);

  doc.setFont('helvetica', 'bold');
  doc.text('Generated At:', margin + 4, currentY + 18);
  doc.setFont('helvetica', 'normal');
  doc.text(generatedDateStr, margin + 27, currentY + 18);

  const col2X = margin + 115;
  doc.setFont('helvetica', 'bold');
  doc.text('Generated By:', col2X, currentY + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(meta.generatedBy || 'District Administrator', col2X + 24, currentY + 6);

  doc.setFont('helvetica', 'bold');
  doc.text('Security Level:', col2X, currentY + 12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(4, 120, 87);
  doc.text('OFFICIAL / RESTRICTED', col2X + 24, currentY + 12);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text('Filter Scope:', col2X, currentY + 18);
  doc.setFont('helvetica', 'normal');
  doc.text(selectedOfficerId === 'all' ? 'All Officers' : `Officer ${selectedOfficerId}`, col2X + 22, currentY + 18);

  currentY += 28;

  // KPI Metrics
  const kpis = [
    { label: 'Total Officers', value: String(meta.totalOfficers || officers.length) },
    { label: 'Active Sessions', value: String(meta.activeOfficers || officers.filter(o => o.status === 'Active').length) },
    { label: 'Total Petitions', value: String(meta.totalPetitions || petitions.length) },
    { label: 'Approved / Resolved', value: String(meta.totalApproved || petitions.filter(p => p.status === 'Approved').length) }
  ];

  const cardW = (pageWidth - (margin * 2) - 9) / 4;
  kpis.forEach((kpi, idx) => {
    const kX = margin + (idx * (cardW + 3));
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(...COLOR_BORDER);
    doc.roundedRect(kX, currentY, cardW, 14, 1.5, 1.5, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...COLOR_NAVY);
    doc.text(kpi.value, kX + (cardW / 2), currentY + 6, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.2);
    doc.setTextColor(...COLOR_SLATE);
    doc.text(kpi.label, kX + (cardW / 2), currentY + 11, { align: 'center' });
  });

  currentY += 19;

  // Section 1: Officers Directory
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_NAVY);
  doc.text('1. Officers Directory & Security Status', margin, currentY);
  currentY += 3;

  const officersTableData = officers.map(off => [
    off.id,
    off.name,
    off.department,
    off.designation,
    off.email || '—',
    off.status === 'Active' ? 'Active' : 'Inactive',
    off.lastLogin ? off.lastLogin.substring(0, 16) : 'Never'
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [['Officer ID', 'Official Name', 'Department / Section', 'Designation', 'Email', 'Status', 'Last Login']],
    body: officersTableData,
    theme: 'grid',
    headStyles: { fillColor: COLOR_NAVY, textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5, textColor: [30, 41, 59], cellPadding: 2 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 24, fontStyle: 'bold' },
      1: { cellWidth: 32 },
      2: { cellWidth: 38 },
      3: { cellWidth: 28 },
      4: { cellWidth: 34 },
      5: { cellWidth: 16, halign: 'center' },
      6: { cellWidth: 20 }
    },
    margin: { left: margin, right: margin }
  });

  currentY = doc.lastAutoTable.finalY + 10;

  // Section 2: Officer-Wise Performance Breakdown
  if (currentY > pageHeight - 50) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_NAVY);
  doc.text('2. Officer-Wise Petition Processing Breakdown & Resolution Rate', margin, currentY);
  currentY += 3;

  const performanceTableData = officers.map(off => [
    off.id,
    off.name,
    off.department,
    String(off.totalProcessed || 0),
    String(off.approved || 0),
    String(off.inProgress || 0),
    String(off.pending || 0),
    off.successRate || '100%'
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [['Officer ID', 'Officer Name', 'Department', 'Total Processed', 'Approved', 'In Review', 'Pending', 'Resolution %']],
    body: performanceTableData,
    theme: 'grid',
    headStyles: { fillColor: [30, 58, 138], textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5, textColor: [30, 41, 59], cellPadding: 2 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 24, fontStyle: 'bold' },
      1: { cellWidth: 36 },
      2: { cellWidth: 44 },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 18, halign: 'center' },
      5: { cellWidth: 18, halign: 'center' },
      6: { cellWidth: 16, halign: 'center' },
      7: { cellWidth: 16, halign: 'center', fontStyle: 'bold' }
    },
    margin: { left: margin, right: margin }
  });

  addOfficialFooters(doc);
  const filename = `Officer_Performance_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
  return filename;
}

/**
 * 2. Generates System Audit Log History PDF
 */
export function generateAuditLogsPdf(reportData, filterOfficerId = 'all') {
  let logs = reportData.recentAuditLogs || [];

  if (filterOfficerId && filterOfficerId !== 'all') {
    logs = logs.filter(l => String(l.officer_id || '').toLowerCase() === String(filterOfficerId).toLowerCase());
  }

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const margin = 14;
  let currentY = 36;

  addOfficialHeader(doc, 'SYSTEM AUDIT & ADMINISTRATIVE SECURITY LOG REPORT');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_NAVY);
  doc.text(`Audit Trail Log — ${filterOfficerId === 'all' ? 'All Officers & Modules' : `Officer ID: ${filterOfficerId}`} (${logs.length} entries)`, margin, currentY);
  currentY += 4;

  const tableData = logs.slice(0, 120).map(l => [
    l.timestamp ? new Date(l.timestamp).toLocaleString('en-IN') : '—',
    l.officer_id || 'SYSTEM',
    l.category || 'GDP Assistant',
    l.action || l.type || 'ACTIVITY',
    l.details || '—'
  ]);

  autoTable(doc, {
    startY: currentY,
    head: [['Timestamp', 'Officer ID', 'Category', 'Action Type', 'Audit Details']],
    body: tableData.length ? tableData : [['—', '—', '—', '—', 'No recorded audit entries found']],
    theme: 'grid',
    headStyles: { fillColor: COLOR_NAVY, textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.2, textColor: [30, 41, 59], cellPadding: 2 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 32 },
      1: { cellWidth: 26, fontStyle: 'bold' },
      2: { cellWidth: 30 },
      3: { cellWidth: 28 },
      4: { cellWidth: 66 }
    },
    margin: { left: margin, right: margin }
  });

  addOfficialFooters(doc);
  const filename = `System_Audit_Log_${filterOfficerId === 'all' ? 'All' : filterOfficerId}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
  return filename;
}

/**
 * 3. Generates Comprehensive Single Petition Dossier PDF
 */
export function generateSinglePetitionPdf(petition) {
  if (!petition) throw new Error('Petition details not found');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  let currentY = 36;

  addOfficialHeader(doc, 'COMPREHENSIVE PETITION DOSSIER & FULL FORM RECORD');

  const petNumber = petition.petitionNumber || petition.id || 'PET-DOCUMENT';

  // Petition Main Banner
  doc.setFillColor(...COLOR_LIGHT_BG);
  doc.setDrawColor(...COLOR_BORDER);
  doc.roundedRect(margin, currentY, pageWidth - (margin * 2), 16, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_NAVY);
  doc.text(`Petition Number: ${petNumber}`, margin + 4, currentY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...COLOR_SLATE);
  doc.text(`Status: ${petition.status || 'Approved'}   |   Priority: ${petition.priority || 'MEDIUM'}   |   Assigned: ${petition.officerName || 'Officer'}`, margin + 4, currentY + 12);

  currentY += 22;

  // Section 1: Petitioner Details Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(...COLOR_NAVY);
  doc.text('1. Applicant Information & Location Hierarchy', margin, currentY);
  currentY += 3;

  autoTable(doc, {
    startY: currentY,
    head: [['Field Description', 'Applicant Record Data', 'Field Description', 'Location & Residence']],
    body: [
      ['Petitioner Name', petition.applicantName || '—', 'District', petition.district || 'Erode'],
      ['Mobile Number', petition.mobile || '—', 'Taluk / Firka', `${petition.taluk || 'Erode'} / ${petition.firka || 'Erode Urban'}`],
      ['Email Address', petition.email || '—', 'Village / Block', `${petition.village || 'Surampatti'} / ${petition.block || 'Erode'}`],
      ['Residential Address', petition.address || 'Erode, Tamil Nadu', 'Intake Channel', petition.intakeChannel || 'Collectorate Public Counter']
    ],
    theme: 'grid',
    headStyles: { fillColor: COLOR_NAVY, textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5, textColor: [30, 41, 59], cellPadding: 2 },
    columnStyles: {
      0: { cellWidth: 38, fontStyle: 'bold' },
      1: { cellWidth: 52 },
      2: { cellWidth: 38, fontStyle: 'bold' },
      3: { cellWidth: 54 }
    },
    margin: { left: margin, right: margin }
  });

  currentY = doc.lastAutoTable.finalY + 8;

  // Section 2: Grievance Classification
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(...COLOR_NAVY);
  doc.text('2. Administrative Grievance Classification & Assignment', margin, currentY);
  currentY += 3;

  autoTable(doc, {
    startY: currentY,
    head: [['Parameter', 'Classification Value', 'Parameter', 'Workflow Information']],
    body: [
      ['Assigned Department', petition.department || 'Revenue Administration', 'Processing Officer', petition.officerName || 'Assigned Officer'],
      ['Grievance Category', petition.category || 'Patta & Land Records', 'Officer ID', petition.officerId || 'ADM-ERODE-001'],
      ['Grievance Sub-Category', petition.subCategory || 'Patta Transfer', 'Submission Date', petition.createdAt ? new Date(petition.createdAt).toLocaleString('en-IN') : '—']
    ],
    theme: 'grid',
    headStyles: { fillColor: [30, 58, 138], textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5, textColor: [30, 41, 59], cellPadding: 2 },
    columnStyles: {
      0: { cellWidth: 38, fontStyle: 'bold' },
      1: { cellWidth: 52 },
      2: { cellWidth: 38, fontStyle: 'bold' },
      3: { cellWidth: 54 }
    },
    margin: { left: margin, right: margin }
  });

  currentY = doc.lastAutoTable.finalY + 8;

  // Section 3: Summary and Action Items
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(...COLOR_NAVY);
  doc.text('3. AI Grievance Summary & Action Points', margin, currentY);
  currentY += 3;

  autoTable(doc, {
    startY: currentY,
    head: [['Section', 'Executive Summary & Recommended Action Trail']],
    body: [
      ['Summary in Tamil\n(மனு சுருக்கம்)', petition.summaryTamil || petition.description || 'மனு விவரங்கள் பதிவு செய்யப்பட்டுள்ளன.'],
      ['English Synopsis', petition.summaryEnglish || petition.description || 'Grievance recorded into the public registry for administrative action.'],
      ['Action Points', Array.isArray(petition.actionItems) && petition.actionItems.length ? petition.actionItems.join('\n') : '1. Field verification by Revenue Inspector\n2. Verification of Village Records\n3. Issuance of DRO Order']
    ],
    theme: 'grid',
    headStyles: { fillColor: COLOR_NAVY, textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5, textColor: [30, 41, 59], cellPadding: 2.5 },
    columnStyles: {
      0: { cellWidth: 42, fontStyle: 'bold' },
      1: { cellWidth: 140 }
    },
    margin: { left: margin, right: margin }
  });

  addOfficialFooters(doc);
  const filename = `Petition_Dossier_${petNumber}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
  return filename;
}

/**
 * 4. Generates Total Petitions Received & Intake Analysis PDF
 */
export function generateIntakeReportPdf(reportData) {
  const meta = reportData.reportMetadata || {};
  const analysis = reportData.intakeAnalysis || {};
  const petitions = reportData.petitionProcessingHistory || [];

  const byChannel = analysis.byChannel || {};
  const byDept = analysis.byDepartment || {};
  const byTaluk = analysis.byTaluk || {};

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const margin = 14;
  let currentY = 36;

  addOfficialHeader(doc, 'TOTAL PETITIONS RECEIVED & MULTI-CHANNEL INTAKE REPORT');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLOR_NAVY);
  doc.text(`Overall Intake Summary: ${meta.totalPetitions || petitions.length} Total Petitions Received`, margin, currentY);
  currentY += 4;

  // Channels Table
  const channelData = Object.entries(byChannel).map(([channel, count]) => [channel, String(count)]);
  autoTable(doc, {
    startY: currentY,
    head: [['CM Grievance Intake Channel', 'Petitions Ingested']],
    body: channelData.length ? channelData : [['Collectorate Public Counter', '1']],
    theme: 'grid',
    headStyles: { fillColor: COLOR_NAVY, textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5, textColor: [30, 41, 59], cellPadding: 2 },
    columnStyles: { 0: { cellWidth: 130 }, 1: { cellWidth: 52, halign: 'center', fontStyle: 'bold' } },
    margin: { left: margin, right: margin }
  });

  currentY = doc.lastAutoTable.finalY + 8;

  // Department Table
  const deptData = Object.entries(byDept).map(([dept, count]) => [dept, String(count)]);
  autoTable(doc, {
    startY: currentY,
    head: [['Department Name', 'Total Grievances']],
    body: deptData.length ? deptData : [['Revenue Administration', '1']],
    theme: 'grid',
    headStyles: { fillColor: [30, 58, 138], textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5, textColor: [30, 41, 59], cellPadding: 2 },
    columnStyles: { 0: { cellWidth: 130 }, 1: { cellWidth: 52, halign: 'center', fontStyle: 'bold' } },
    margin: { left: margin, right: margin }
  });

  currentY = doc.lastAutoTable.finalY + 8;

  // Taluk Table
  const talukData = Object.entries(byTaluk).map(([taluk, count]) => [taluk, String(count)]);
  autoTable(doc, {
    startY: currentY,
    head: [['Taluk Allocation', 'Total Petitions']],
    body: talukData.length ? talukData : [['Erode', '1']],
    theme: 'grid',
    headStyles: { fillColor: COLOR_NAVY, textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5, textColor: [30, 41, 59], cellPadding: 2 },
    columnStyles: { 0: { cellWidth: 130 }, 1: { cellWidth: 52, halign: 'center', fontStyle: 'bold' } },
    margin: { left: margin, right: margin }
  });

  addOfficialFooters(doc);
  const filename = `Total_Petitions_Received_Report_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
  return filename;
}
